#系统配置
sys:
  localFilePath: H:\ftpRead
#  localFilePath: /usr/ftpFile
  fileMaxSize: 50

#ftp设置
ftp:
  host: 127.0.0.1
#  host: 192.168.30.101
  port: 21
  user: test
  password: 123456
  filePath: /
  isActiveType: true